[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Optional: If you want to use the functions without the .netlify prefix
[[redirects]]
  from = "/codes"
  to = "/.netlify/functions/codes"
  status = 200

[[redirects]]
  from = "/codes/*"
  to = "/.netlify/functions/codes/:splat"
  status = 200

[[redirects]]
  from = "/logs" 
  to = "/.netlify/functions/logs"
  status = 200
  
[[redirects]]
  from = "/open"
  to = "/.netlify/functions/open"
  status = 200

# Environment variables for build (you'll need to set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"
